'''
https://leetcode.com/problems/find-the-difference/
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.
'''
'''
Time:O(n)
Space:O(1)
'''
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        d = Counter(s)
        for i in t:
            if i not in d or d[i]==0:
                return i
            else:
                d[i] -= 1
                
'''
Bit manipulation.
Time:O(n)
Space:O(1)
'''
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        ch = 0
        for i in s:
            ch = ch^ord(i)
        for j in t:
            ch = ch^ord(j)
        return chr(ch)
