'''
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.
'''

'''
Method belows uses hashmap.
Time:O(n)
Space:O(1)
'''
class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        dict = {}
        for i in s:
            if i in dict:
                dict[i] += 1
            else:
                dict[i] = 1
        for i in t:
            if i not in dict or dict[i]==0:
                return i
            else:
                dict[i] = dict[i]-1


 '''
 Method below uses sorted function.
 Time:O(n lg(n))
 Space:O(n)
 '''
 class Solution(object):
    def findTheDifference(self, s, t):
        s=sorted(s)
        t=sorted(t)
        i = 0
        while i < len(s):
            if s[i] != t[i]:
                return t[i]
            i += 1
        return t[-1]
